trigger:
  batch: true
  branches:
    include:
      - dev

pr:
  branches:
    include:
      - dev
  autoCancel: true
  drafts: false

variables:
  - template: variables.yml

stages:
  - stage: TestStage
    displayName: Sag mal bist du jetzt devops oder was?
    pool:
      vmImage: $(vmImage)

    jobs:
      - template: templates/setup.yml
        parameters:
          DotnetSdkVersion: $(netSdkVersion)

      - template: templates/versioning.yml
        parameters:
          DependsOn:
            - setup

      - template: templates/restore.yml
        parameters:
          ProjectPath: $(projectPath)
          ProjectName: $(projectName)
          BuildConfiguration: $(buildConfiguration)
          VstsFeed: $(internalFeedName)
          DependsOn:
            - setup

      - template: templates/build.yml
        parameters:
          ProjectPath: $(projectPath)
          ProjectName: $(projectName)
          BuildConfiguration: $(buildConfiguration)
          DependsOn:
            - restore

      - template: templates/pack.yml
        parameters:
          ProjectPath: $(projectPath)
          ProjectName: $(projectName)
          BuildConfiguration: $(buildConfiguration)
          DependsOn:
            - build

      - template: templates/test.yml
        parameters:
          ProjectName: $(projectName)
          BuildConfiguration: $(buildConfiguration)
          DependsOn:
            - pack

      - template: templates/push.yml
        parameters:
          ProjectName: $(projectName)
          NugetFeedType: "internal"
          VstsFeed: $(internalFeedName)
          AllowPackageConflicts: true
          DependsOn:
            - pack
