variables:
  - name: netSdkVersion
    value: 7.0.x
  - name: buildConfiguration
    value: Release
  - name: vmImage
    value: ubuntu-latest
  - name: solutionPath
    value: src/Snowflake.Net.sln
  - name: projectPath
    value: src/Snowflake.Net/Snowflake.Net.csproj
  - name: internalFeedName
    value: Snowflake.Net/Snowflake.Net